# Generated by Django 4.0.5 on 2022-06-17 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_todoitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='complete',
        ),
    ]
