# Generated by Django 4.0.5 on 2022-06-17 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_todoitem_complete'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TodoItem',
        ),
    ]
